version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5000:5000"
    environment:
       POSTGRES_DB: dockerdb
       POSTGRES_PASSWORD: postgres
  
  web:
    image: barns-app:v0.1
    ports:
      - "3000:3000"
    restart: always
    