version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "54320:5432"
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
  
  web:
    image: barns-app:v0.1
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - db
    